---
title: "git_00"
author: "Juan Padilla"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
Beware the Jabberwock, my son!    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea, Shining with all his might:  
He did his very best to make the billows smooth and bright  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
In my sky at twilight you are like a cloud  
and your form and colour are the way I love them.  
You are mine, mine, woman with sweet lips  
and in your life my infinite dreams live.  

The lamp of my soul dyes your feet,  
the sour wine is sweeter on your lips,  
oh reaper of my evening song,  
how solitary dreams believe you to be mine!  

You are mine, mine, I go shouting it to the afternoon's  
wind, and the wind hauls on my widowed voice.  
Huntress of the depth of my eyes, your plunder  
stills your nocturnal regard as though it were water.  

You are taken in the net of my music, my love,  
and my nets of music are wide as the sky.  
My soul is born on the shore of your eyes of mourning.  
In your eyes of mourning the land of dreams begin.  